# Generated by Django 5.2.6 on 2025-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('bruto', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('suscriptores', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('main_pier', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
